---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, ransomware protection' 
summary: 瞭解勒索軟體保護的新功能。 
---
= 勒索軟體保護的新功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
瞭解勒索軟體保護的新功能。



== 2022年6月12日



=== NAS檔案系統稽核狀態現在會針對ONTAP 您的不完整儲存VM進行追蹤

如果工作環境中少於40%的儲存VM啟用檔案系統稽核、則會在_Cyber Resilience Map_中新增警示。您可以在「_Harden Your ONTAP Sfor enapenity_」面板中、檢視未追蹤SMB和NFS事件的確切SVM數、並將其記錄到稽核記錄檔中。然後您可以決定是否對這些SVM啟用稽核。



=== 當您的磁碟區未啟用隨裝即用的勒索軟體時、就會顯示警示

此資訊已在ONTAP 「_Harden Your ONTAP Sfor the Ezenology_」面板中報告、 但現在、當開箱內的勒索軟體功能在不到40%的磁碟區中開啟時、_網路還原地圖_會報告警示、以便您在儀表板中檢視此資訊。



=== 現在ONTAP 、我們會追蹤FSX for Sfor Sfor Sfor Sfor Sfor Systems以啟用Volume快照

「_Harden Your ONTAP Sfor Ezh enievenienials_」面板現在提供FSX for ONTAP EzSystems上Volume的Snapshot複本狀態。如果有不到40%的磁碟區受到快照保護、您也會在_網路還原地圖_中收到警示。



== 2022年5月11日



=== 全新面板可追蹤ONTAP 您的不穩定環境的安全強化。

全新的面板_Harden Your ONTAP SUREYS段 環境_提供ONTAP 您的某些支援系統設定的狀態、可追蹤您的部署安全程度、並根據 https://www.netapp.com/pdf.html?item=/media/10674-tr4569.pdf["《NetApp ONTAP 資訊系統安全強化指南》"^] 以及 https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["介紹防勒索軟體功能ONTAP"^] 主動偵測異常活動並提出警告。

您可以檢閱建議、然後決定如何解決潛在問題。您可以依照步驟變更叢集上的設定、將變更延後至其他時間、或忽略建議。 https://docs.netapp.com/us-en/cloud-manager-ransomware/task-analyze-ransomware-data.html#status-of-ontap-systems-hardening["如需詳細資料、請前往此處"]。



=== 新的面板可顯示如何使用Cloud Backup來保護不同類別的資料。

這個全新的「備份狀態」面板顯示、如果您因為勒索軟體攻擊而需要恢復、最重要的資料類別將會備份得多麼完整。此資料可視覺化呈現由Cloud Backup備份環境中特定類別的項目數量。 https://docs.netapp.com/us-en/cloud-manager-ransomware/task-analyze-ransomware-data.html#backup-status-of-your-critical-business-data["如需詳細資料、請前往此處"]。



== 2022年3月15日



=== 新的面板可追蹤業務關鍵資料的權限狀態

新的「業務關鍵資料權限分析」面板會顯示資料的權限狀態、這對您的業務而言至關重要。如此一來、您就能快速評估保護業務關鍵資料的能力。 https://docs.netapp.com/us-en/cloud-manager-ransomware/task-analyze-ransomware-data.html#status-of-permissions-on-your-critical-business-data["如需詳細資料、請前往此處"]。



=== 「開放權限」區域現在包括OneDrive和SharePoint帳戶

勒索軟體保護儀表板中的「開放權限」區域現在包含OneDrive帳戶和SharePoint帳戶中掃描檔案的權限。



== 2022年2月9日



=== 全新勒索軟體保護服務

全新的勒索軟體保護服務可讓您檢視網路安全相關資訊、並評估資料對網路攻擊的恢復能力。它也提供警示與修正清單、讓您的資料更安全。

link:concept-ransomware-protection.html["深入瞭解這項新服務"]。
